# Generated by Django 2.2.12 on 2021-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehgienpartner',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
