# Generated by Django 2.1.3 on 2019-08-06 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_hotels_markets_shopping_worship'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaPrimarySchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField()),
                ('name_of_sc', models.CharField(max_length=80)),
                ('level_field', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
                ('schsponsor', models.CharField(max_length=80)),
                ('type1', models.CharField(max_length=80)),
                ('type2', models.CharField(max_length=80)),
                ('type3', models.CharField(max_length=80)),
                ('pupilteach', models.FloatField()),
                ('classrmrat', models.FloatField()),
                ('toiletrati', models.FloatField()),
                ('no_classrm', models.BigIntegerField()),
                ('boystoilet', models.BigIntegerField()),
                ('girlstoile', models.BigIntegerField()),
                ('teachersto', models.BigIntegerField()),
                ('totaltoile', models.BigIntegerField()),
                ('totalboys', models.BigIntegerField()),
                ('totalgirls', models.BigIntegerField()),
                ('totalenrol', models.BigIntegerField()),
                ('go_ktsc_m', models.BigIntegerField()),
                ('gok_tsc_f', models.BigIntegerField()),
                ('authoritym', models.BigIntegerField()),
                ('authorityf', models.BigIntegerField()),
                ('pta_bog_m', models.BigIntegerField()),
                ('pta_bog_f', models.BigIntegerField()),
                ('othersm', models.BigIntegerField()),
                ('othersf', models.BigIntegerField()),
                ('noteaching', models.BigIntegerField()),
                ('nonteachin', models.BigIntegerField()),
                ('province', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('division', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('costituenc', models.CharField(max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'KenyaPrimarySchools',
            },
        ),
        migrations.CreateModel(
            name='SecondarySchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'SecondarySchools',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('descriptio', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UniversitiesColleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('descriptio', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'UniversitiesColleges',
            },
        ),
        migrations.RenameModel(
            old_name='Shopping',
            new_name='KenyaNationalPolytechnics',
        ),
        migrations.RenameModel(
            old_name='Worship',
            new_name='PrivateColleges',
        ),
        migrations.RenameModel(
            old_name='Hotels',
            new_name='PrivateUniversities',
        ),
        migrations.RenameModel(
            old_name='Markets',
            new_name='PublicColleges',
        ),
        migrations.RenameModel(
            old_name='Health',
            new_name='TeachersTrainingColleges',
        ),
        migrations.AlterModelOptions(
            name='kenyanationalpolytechnics',
            options={'verbose_name_plural': 'KenyaNationalPolytechnics'},
        ),
        migrations.AlterModelOptions(
            name='privatecolleges',
            options={'verbose_name_plural': 'PrivateColleges'},
        ),
        migrations.AlterModelOptions(
            name='privateuniversities',
            options={'verbose_name_plural': 'PrivateUniversities'},
        ),
        migrations.AlterModelOptions(
            name='publiccolleges',
            options={'verbose_name_plural': 'PublicColleges'},
        ),
        migrations.AlterModelOptions(
            name='teacherstrainingcolleges',
            options={'verbose_name_plural': 'TeachersTrainingColleges'},
        ),
    ]
