# Generated by Django 2.2.12 on 2020-05-21 11:38

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('NormalUser', 'normaluser'), ('Agent', 'agent'), ('PropertyManager', 'property_manager'), ('design&servicePro', 'design&service_pro')], default='NormalUser', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('license_number', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('website_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('speciality', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Buying and Selling of houses'), ('2', 'Renting houses'), ('3', 'Leasing office spaces'), ('4', 'Buying and selling of land')], default='1', max_length=7, null=True)),
                ('about', ckeditor.fields.RichTextField(blank=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium Agent', 'Premium Agent')], default='Basic', max_length=10)),
                ('featured_agent', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgentProfiles',
            },
        ),
        migrations.CreateModel(
            name='DesignAndServiceProProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('about', ckeditor.fields.RichTextField(blank=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium account', 'Premium account')], default='Basic', max_length=10)),
                ('pro_speciality', models.CharField(blank=True, choices=[('Interior Designer', 'Interior Designer'), ('Architect', 'Architect'), ('Landscape architect', 'Landscape architect'), ('Home mover', 'Home mover'), ('Plumbing', 'Plumbing'), ('Photographer', 'Photographer')], max_length=20, null=True)),
                ('featured_pro', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='DService_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DesignAndServiceProProfiles',
            },
        ),
        migrations.CreateModel(
            name='PropertyManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('license_number', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('website_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('about', ckeditor.fields.RichTextField(blank=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium Manager', 'Premium Manager')], default='Basic', max_length=10)),
                ('featured_agent', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyManagerProfiles',
            },
        ),
        migrations.CreateModel(
            name='PropertyManagerReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Never'), (2, 'Not likely'), (3, 'Mybe'), (4, 'Likely'), (5, 'Highly likely')], null=True)),
                ('responsive_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('communication_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('attention_to_detail', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('service', models.CharField(choices=[('1', 'Helped me find tenants.'), ('2', 'Helped me find a rental.'), ('3', 'Consultation.'), ('4', 'Listed my property on Rehgien.'), ('5', 'None. Reached out but agent never responded.'), ('6', 'Managed(s) my property.'), ('7', 'Other real estate service.')], max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
                ('date_of_service', models.DateField(null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_review', to='profiles.PropertyManagerProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyManagerReviews',
            },
        ),
        migrations.CreateModel(
            name='NormalUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NormalUserProfiles',
            },
        ),
        migrations.CreateModel(
            name='DesignAndServiceProReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Never'), (2, 'Not likely'), (3, 'Mybe'), (4, 'Likely'), (5, 'Highly likely')], null=True)),
                ('quality_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('creativity_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('attention_to_detail', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('comment', models.TextField(null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DService_review', to='profiles.DesignAndServiceProProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DService_review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DesignAndServiceProReviews',
            },
        ),
        migrations.CreateModel(
            name='AgentReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Never'), (2, 'Not likely'), (3, 'Mybe'), (4, 'Likely'), (5, 'Highly likely')], null=True)),
                ('responsive_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('knowledge_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('negotiation_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('professionalism_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('service', models.CharField(choices=[('1', 'Helped me sell my home.'), ('2', 'Helped me find tenants.'), ('3', 'Helped me buy a home.'), ('4', 'Helped me find a rental.'), ('5', 'Consultation.'), ('6', 'Listed my property on Rehgien.'), ('7', 'None. Reached out but agent never responded.'), ('8', 'Managed(s) my property.')], max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
                ('date_of_service', models.DateField(null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_review', to='profiles.AgentProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgentReviews',
            },
        ),
    ]
