# Generated by Django 2.1.3 on 2020-04-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('license_number', models.CharField(blank=True, max_length=250)),
                ('about', models.TextField(blank=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('Agent', 'Agent')], default='Agent', max_length=10)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
