# Generated by Django 2.1.3 on 2019-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number', max_length=10),
        ),
    ]
