# Generated by Django 2.1.3 on 2019-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190717_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='name',
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
    ]
