# Generated by Django 2.2.12 on 2020-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201123_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pro_category',
            field=models.CharField(choices=[('PCAT1', 'realestate services'), ('PCAT2', 'surveying and construction'), ('PCAT3', 'architecture and building design'), ('PCAT4', 'general services'), ('PCAT5', 'renovation and remodeling'), ('PCAT6', 'appliances and systems'), ('PCAT7', 'cleaning services')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pro_speciality',
            field=models.CharField(choices=[('VALUERS', 'valuers'), ('REALESTATE_AGENTS', 'realestate agents'), ('PROPERTY_MANAGERS', 'property managers'), ('FACILITY_MANAGERS', 'facility managers'), ('BUILDING_INSPECTORS', 'building inspectors'), ('LAND_SURVEYORS', 'land surveyors'), ('QUANTITY_SURVEYORS', 'quantity surveyors'), ('CONSTRUCTION_MANAGERS', 'construction managers'), ('ARCHITECTS', 'architects'), ('LANDSCAPE_ARCHITECTS', 'landscape architects'), ('LANDSCAPE_DESIGNERS', 'landscape designers'), ('GENERAL_CONTRACTORS', 'general contrators'), ('LANDSCAPE_CONTRACTORS', 'landscape contractors'), ('INTERIOR_DESIGNERS_AND_DECORATORS', 'interior designers and decorators'), ('PHOTOGRAPHERS', 'photographers'), ('MOVERS', 'movers'), ('CARPENTERS', 'carpenters'), ('DOOR_DEALERS', 'door dealers'), ('CARPET_DEALERS', 'carpet dealers'), ('BUILDING_SUPPLIES_SUPPLIERS', 'building supplies suppliers'), ('PLUMBERS', 'plumbers'), ('HOME_AUTOMATION_AND_HOME_MEDIA', 'home automation and home media'), ('ELECTRICIANS', 'electricians'), ('SOLAR_ENERGY_SYSTEMS', 'solar energy systems'), ('HOUSE_CLEANERS', 'house cleaners'), ('CARPET_AND_UPHOLSTERY_CLEANERS', 'carpet and upholstery cleaners'), ('WINDOW_CLEANERS', 'window cleaners'), ('GARBAGE_CLEANERS', 'garbage cleaners'), ('PEST_CONTROL', 'pest control'), ('EXTERIOR_CLEANERS', 'exterior cleaners')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=models.CharField(blank=True, choices=[('REALESTATE_VALUATION', 'realestate valuation'), ('LAND_VALUATION', 'land valuation'), ('PROPERTY_CONSULTANCY', 'property consultancy'), ('BUYING_AND_SELLING_PROPERTY', 'buying and selling property'), ('PROPERTY_LISTING', 'property listing'), ('PROPERTY_MANAGEMENT', 'property management'), ('FACILITY_MANAGEMENT', 'facility management'), ('BUILDING_CONDITION_ASSESSMENT', 'building condition asessment'), ('LAND_SERVEYING', 'land surveying')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='porfolio_item_type',
            field=models.CharField(choices=[('REALESTATE_MANAGEMENT', 'realestate management'), ('PROJECT_MANAGEMENT', 'project management'), ('CONSTRUCTION_PROJECT', 'construction project'), ('PROJECT_SALE', 'project sale'), ('REALESTATE_SALE', 'realestate sale')], max_length=100, null=True),
        ),
    ]
