# Generated by Django 2.2.12 on 2020-09-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200816_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NormalUser', 'NormalUser'), ('Agent', 'Agent'), ('PropertyManager', 'PropertyManager'), ('Design&servicePro', 'Design&servicePro'), ('Admin', 'Admin')], default='NormalUser', max_length=20),
        ),
        migrations.DeleteModel(
            name='NormalUserProfile',
        ),
    ]
