# Generated by Django 2.2.12 on 2020-09-20 07:43

import ckeditor.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200920_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='designandserviceproprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NormalUser', 'NormalUser'), ('Agent', 'Agent'), ('PropertyManager', 'PropertyManager'), ('Design&servicePro', 'Design&servicePro'), ('Company', 'Company'), ('Admin', 'Admin')], default='NormalUser', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('Property Management', 'Property Management'), ('Agency', 'Agency')], default='Property Management', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('license_number', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('website_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('about', ckeditor.fields.RichTextField(blank=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium Agent', 'Premium Agent')], default='Basic', max_length=10)),
                ('featured_agent', models.BooleanField(blank=True, default=False, null=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='company_agents', to=settings.AUTH_USER_MODEL)),
                ('property_managers', models.ManyToManyField(blank=True, related_name='company_pms', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CompanyProfiles',
            },
        ),
    ]
