# Generated by Django 2.2.12 on 2020-09-20 07:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200920_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='speciality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Property Management', 'Property Management'), ('Agency', 'Agency')], default='Property Management', max_length=100),
        ),
    ]
