# Generated by Django 2.2.12 on 2020-09-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200920_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='featured_agent',
            new_name='featured_business',
        ),
    ]
