# Generated by Django 2.2.12 on 2020-11-28 10:19

from django.db import migrations, models
import embed_video.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_businessprofile_short_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='about_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('REALESTATE_VALUATION', 'realestate valuation'), ('LAND_VALUATION', 'land valuation'), ('PROPERTY_CONSULTANCY', 'property consultancy'), ('BUYING_AND_SELLING_PROPERTY', 'buying and selling property'), ('PROPERTY_LISTING', 'property listing'), ('PROPERTY_MANAGEMENT', 'property management'), ('FACILITY_MANAGEMENT', 'facility management'), ('BUILDING_CONDITION_ASSESSMENT', 'building condition asessment'), ('LAND_SURVEYING', 'land surveying')], default=None, max_length=186, null=True),
        ),
    ]
