# Generated by Django 2.2.12 on 2020-09-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200920_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='speciality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Property Management', 'Property Management'), ('Agency', 'Agency'), ('Consultancy', 'Consultancy')], default='Property Management', max_length=100),
        ),
        migrations.CreateModel(
            name='CompanyReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Never'), (2, 'Not likely'), (3, 'Mybe'), (4, 'Likely'), (5, 'Highly likely')], null=True)),
                ('responsive_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('knowledge_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('negotiation_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('professionalism_rating', models.PositiveIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')], null=True)),
                ('service', models.CharField(choices=[('1', 'Helped me sell my home.'), ('2', 'Helped me find tenants.'), ('3', 'Helped me buy a home.'), ('4', 'Helped me find a rental.'), ('5', 'Consultation.'), ('6', 'Listed my property on Rehgien.'), ('7', 'None. Reached out but never responded.'), ('8', 'Managed(s) my property.')], max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
                ('date_of_service', models.DateField(null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='profiles.CompanyProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgentReviews',
            },
        ),
    ]
