# Generated by Django 2.2.12 on 2020-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200920_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyreviews',
            options={'verbose_name_plural': 'CompanyReviews'},
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='designandserviceproprofile',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='propertymanagerprofile',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
    ]
