# Generated by Django 2.2.12 on 2020-09-27 11:04

import cloudinary.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200921_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAndServiceProProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('project_description', models.TextField(null=True)),
                ('project_video', models.URLField(blank=True, max_length=300, null=True)),
                ('project_location', models.CharField(max_length=200, null=True)),
                ('project_map_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('project_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DService_projects', to='profiles.DesignAndServiceProProfile')),
            ],
            options={
                'verbose_name_plural': 'DesignAndServiceProProjects',
            },
        ),
        migrations.CreateModel(
            name='DSProProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DS_project_Images', to='profiles.DesignAndServiceProProjects')),
            ],
        ),
    ]
