# Generated by Django 2.2.12 on 2020-09-27 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_designandserviceproprojects_dsproprojectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designandserviceproprojects',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='designandserviceproprojects',
            name='project_date',
        ),
        migrations.AddField(
            model_name='designandserviceproprojects',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='DS_project_ls_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designandserviceproprojects',
            name='project_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
