# Generated by Django 2.2.12 on 2020-12-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201222_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_of_service',
        ),
    ]
