# Generated by Django 2.2.12 on 2020-12-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_review_date_of_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='quality_rating',
            new_name='quality_of_service_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='recommendation_rating',
        ),
    ]
