# Generated by Django 2.2.12 on 2020-09-27 12:45

import cloudinary.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200927_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, null=True)),
                ('property_market_value', models.PositiveIntegerField(null=True)),
                ('property_location', models.CharField(max_length=200, null=True)),
                ('property_map_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('manager_from', models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('manager_to', models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PM_portfolio_ls_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PMPortfolio',
            },
        ),
        migrations.CreateModel(
            name='PMPortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_porfolio_Images', to='profiles.PMPortfolio')),
            ],
        ),
    ]
