# Generated by Django 2.2.12 on 2020-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_pmportfolio_pmportfolioimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='designandserviceproprojects',
            name='project_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
