# Generated by Django 2.2.12 on 2020-12-23 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='liked_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
