# Generated by Django 2.2.12 on 2020-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200927_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmportfolio',
            name='currently_managing',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
    ]
