# Generated by Django 2.2.12 on 2020-10-02 23:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200927_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designandserviceproprojects',
            name='project_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
