# Generated by Django 2.2.12 on 2021-01-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210102_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalcategory',
            options={'verbose_name_plural': 'ProfessionalCategories'},
        ),
        migrations.AlterModelOptions(
            name='professionalgroup',
            options={'verbose_name_plural': 'ProfessionalGroups'},
        ),
        migrations.AlterModelOptions(
            name='professionalservice',
            options={'verbose_name_plural': 'ProfessionalServices'},
        ),
        migrations.AlterField(
            model_name='professionalcategory',
            name='professional_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pro_category_group', to='profiles.ProfessionalGroup'),
        ),
    ]
