# Generated by Django 2.2.12 on 2020-10-03 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20201003_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='agent_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='agent_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='company_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='company_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designandserviceproprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='ds_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designandserviceproprofile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='ds_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymanagerprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='pm_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymanagerprofile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='pm_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
