# Generated by Django 2.2.12 on 2020-10-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20201003_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proTeamModel', to=settings.AUTH_USER_MODEL)),
                ('team_mates', models.ManyToManyField(blank=True, null=True, related_name='proTeamMates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
