# Generated by Django 2.2.12 on 2020-10-03 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profesionalteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalteam',
            name='team_mates',
            field=models.ManyToManyField(blank=True, related_name='proTeamMates', to=settings.AUTH_USER_MODEL),
        ),
    ]
