# Generated by Django 2.2.12 on 2021-01-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210102_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='professionalgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
