# Generated by Django 2.2.12 on 2020-10-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201004_0324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teammate',
            new_name='TeammateConnection',
        ),
    ]
