# Generated by Django 2.2.12 on 2020-10-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20201004_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='property_managers',
        ),
    ]
