# Generated by Django 2.2.12 on 2020-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20201004_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammateconnection',
            name='starred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
