# Generated by Django 2.2.12 on 2020-10-08 14:50

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_teammateconnection_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('client_name', models.CharField(max_length=25)),
                ('business_category', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_top_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TopClients',
            },
        ),
    ]
