# Generated by Django 2.2.12 on 2021-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20210128_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_profile_images/'),
        ),
    ]
