# Generated by Django 2.2.12 on 2021-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_kenyatown'),
        ('profiles', '0024_auto_20210128_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='service_area2',
            field=models.ManyToManyField(blank=True, related_name='pro_service_services', to='location.KenyaTown'),
        ),
    ]
