# Generated by Django 2.2.12 on 2021-01-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_businessprofile_service_area2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='service_areas',
        ),
    ]
