# Generated by Django 2.2.12 on 2020-10-28 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20201008_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='service_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
