# Generated by Django 2.2.12 on 2020-10-31 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_agentprofile_service_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
