# Generated by Django 2.2.12 on 2020-10-31 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20201031_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
