# Generated by Django 2.2.12 on 2021-02-11 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20210211_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
