# Generated by Django 2.2.12 on 2020-11-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20201102_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceArea',
        ),
    ]
