# Generated by Django 2.2.12 on 2020-11-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_delete_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.BooleanField(default=True)),
                ('part_time', models.BooleanField(default=False)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='business_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ag_business_hours', to='profiles.BusinessHours'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='business_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_business_hours', to='profiles.BusinessHours'),
        ),
        migrations.AddField(
            model_name='designandserviceproprofile',
            name='business_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ds_business_hours', to='profiles.BusinessHours'),
        ),
        migrations.AddField(
            model_name='propertymanagerprofile',
            name='business_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_business_hours', to='profiles.BusinessHours'),
        ),
    ]
