# Generated by Django 2.2.12 on 2021-02-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_professionalgroup_group_image_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalgroup',
            name='group_image',
        ),
    ]
