# Generated by Django 2.2.12 on 2020-11-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20201102_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ('weekday', 'from_hour'), 'verbose_name_plural': 'BusinessHours'},
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='designandserviceproprofile',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('weekday', 'from_hour', 'to_hour')},
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='full_time',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='part_time',
        ),
    ]
