# Generated by Django 2.2.12 on 2021-02-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_professionalgroup_group_image_new'),
    ]

    operations = [
    ]
