# Generated by Django 2.2.12 on 2020-11-03 15:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20201102_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTopClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('client_name', models.CharField(max_length=25)),
                ('business_category', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ag_top_clients', to='profiles.CompanyProfile')),
            ],
            options={
                'verbose_name_plural': 'AgentTopClients',
            },
        ),
        migrations.CreateModel(
            name='CompanyTopClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('client_name', models.CharField(max_length=25)),
                ('business_category', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_top_clients', to='profiles.CompanyProfile')),
            ],
            options={
                'verbose_name_plural': 'CompanyTopClients',
            },
        ),
        migrations.CreateModel(
            name='DSTopClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('client_name', models.CharField(max_length=25)),
                ('business_category', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_top_clients', to='profiles.CompanyProfile')),
            ],
            options={
                'verbose_name_plural': 'DSTopClients',
            },
        ),
        migrations.CreateModel(
            name='PropertyMangerTopClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('client_name', models.CharField(max_length=25)),
                ('business_category', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_top_clients', to='profiles.CompanyProfile')),
            ],
            options={
                'verbose_name_plural': 'PropertyMangerTopClients',
            },
        ),
        migrations.DeleteModel(
            name='TopClient',
        ),
    ]
