# Generated by Django 2.2.12 on 2020-11-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20201103_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyMangerTopClient',
            new_name='PropertyManagerTopClient',
        ),
        migrations.AlterModelOptions(
            name='propertymanagertopclient',
            options={'verbose_name_plural': 'PropertyManagerTopClients'},
        ),
        migrations.AlterField(
            model_name='agenttopclient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ag_top_clients', to='profiles.AgentProfile'),
        ),
        migrations.AlterField(
            model_name='dstopclient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_top_clients', to='profiles.DesignAndServiceProProfile'),
        ),
        migrations.AlterField(
            model_name='propertymanagertopclient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_top_clients', to='profiles.PropertyManagerProfile'),
        ),
    ]
