# Generated by Django 2.2.12 on 2021-10-03 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254xxxxxxxxx'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of times otp has been sent')),
                ('verified', models.BooleanField(default=False, help_text='If otp verification got successful')),
            ],
            options={
                'verbose_name_plural': 'Reset Password OTP',
            },
        ),
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'verbose_name_plural': 'Phone Otp'},
        ),
    ]
