# Generated by Django 2.2.12 on 2021-10-11 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20211003_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalgroup',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='group_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
