# Generated by Django 2.2.12 on 2021-10-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_professionalgroup_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='professional_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_category', to='profiles.ProfessionalCategory'),
        ),
    ]
