# Generated by Django 2.2.12 on 2021-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20211017_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptions',
            name='name',
            field=models.CharField(blank=True, help_text='Option name', max_length=100, null=True),
        ),
    ]
