# Generated by Django 2.2.12 on 2021-10-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_auto_20211017_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_options',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_option', to='profiles.Question'),
        ),
    ]
