# Generated by Django 2.2.12 on 2021-10-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_auto_20211017_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmaker',
            options={'verbose_name_plural': 'Matchmaking Process'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Matchmaking Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='client_question',
            field=models.TextField(help_text='The question that clients will be asked e.g. How many rooms are you painting?', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='pro_question',
            field=models.TextField(help_text='The question that professionals will be asked?', null=True),
        ),
    ]
