# Generated by Django 2.2.12 on 2021-10-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_proanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='ClientAnswer',
        ),
    ]
