# Generated by Django 2.2.12 on 2021-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20211019_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='proanswer',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='pro_option_answer', to='profiles.QuestionOptions'),
        ),
    ]
