# Generated by Django 2.2.12 on 2021-10-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_kenyatown'),
        ('profiles', '0057_auto_20211019_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesearchhistory',
            name='project_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_location_service_search_history', to='location.KenyaTown'),
        ),
    ]
