# Generated by Django 2.2.12 on 2021-10-20 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_kenyatown'),
        ('profiles', '0058_servicesearchhistory_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='project_cost',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_duration',
            field=models.PositiveIntegerField(help_text='Project duration_in days', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_job_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_job_type', to='profiles.ProfessionalService'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_location', to='location.KenyaTown'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_year',
            field=models.PositiveIntegerField(default=2021, null=True, validators=[django.core.validators.MinValueValidator(1984), profiles.models.max_value_current_year]),
        ),
    ]
