# Generated by Django 2.2.12 on 2022-01-20 11:05

import django.core.validators
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_user_azure_token_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_year',
            field=models.PositiveIntegerField(default=2022, null=True, validators=[django.core.validators.MinValueValidator(1984), profiles.models.max_value_current_year]),
        ),
    ]
