# Generated by Django 2.2.12 on 2022-07-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0063_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalgroup',
            name='group_category',
            field=models.CharField(blank=True, choices=[('PROFESSIONALS', 'Professionals'), ('ORDER_AND_DELIVERY', 'Order and delivery')], default='PROFESSIONALS', max_length=50, null=True),
        ),
    ]
