# Generated by Django 2.2.12 on 2020-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20201121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
    ]
