# Generated by Django 2.2.12 on 2020-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20201225_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
