# Generated by Django 2.2.12 on 2022-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
