# Generated by Django 2.2.12 on 2022-01-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_auto_20220120_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='question',
        ),
    ]
