# Generated by Django 2.2.12 on 2020-08-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('MANSION', 'Mansion'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium')], max_length=20)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('max_beds', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('additional_details', models.TextField()),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent')], max_length=20)),
                ('timeline', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('claimer', models.ManyToManyField(blank=True, related_name='Prop_lead_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prop_lead_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyRequests',
            },
        ),
        migrations.CreateModel(
            name='ProffesionalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_proffesional', models.CharField(choices=[('AGENT', 'Agent'), ('PROPERTYMANAGER', 'Property Manager'), ('INTERIORDESIGNER', 'Interior Designer'), ('ARCHITECT', 'Architect'), ('LANDSCAPEARCHITECT', 'Landscape architect'), ('HOMEMOVER', 'Home mover'), ('PLUMBING', 'Plumbing'), ('PHOTOGRAPHER', 'Photographer')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('service_details', models.TextField()),
                ('timeline', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('claimer', models.ManyToManyField(blank=True, related_name='Prof_lead_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_lead_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ProffesionalRequests',
            },
        ),
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('service_details', models.TextField()),
                ('timeline', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('claimer', models.ManyToManyField(blank=True, related_name='Other_request_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Other_request_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OtherRequests',
            },
        ),
    ]
