# Generated by Django 2.2.12 on 2020-11-21 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLeadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('price_negotiable', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location_name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('general_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=18)),
                ('parking_choices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=34)),
                ('additional_details', models.TextField()),
                ('market_value', models.PositiveIntegerField(default=None)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('ownership', models.CharField(choices=[('BUYER', 'Buyer'), ('RENTER', 'Renter'), ('LESSEE', 'Lessee')], max_length=20)),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, max_length=250)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AgentLeadRequests',
            },
        ),
        migrations.CreateModel(
            name='AgentPropertyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow')], max_length=20)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('max_beds', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location_name', models.CharField(max_length=50)),
                ('general_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=18)),
                ('parking_choices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=34)),
                ('additional_details', models.TextField()),
                ('market_value', models.PositiveIntegerField(default=None)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent'), ('LEASE', 'Lease')], max_length=20)),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, max_length=250)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AgentPropertyRequests',
            },
        ),
        migrations.CreateModel(
            name='OtherServiceLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('service_details', models.TextField()),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, max_length=250)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'OtherServiceLeads',
            },
        ),
        migrations.CreateModel(
            name='ProffesionalRequestLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_proffesional', models.CharField(choices=[('AGENT', 'Agent'), ('PROPERTYMANAGER', 'Property Manager'), ('INTERIORDESIGNER', 'Interior Designer'), ('ARCHITECT', 'Architect'), ('LANDSCAPEARCHITECT', 'Landscape architect'), ('HOMEMOVER', 'Home mover'), ('PLUMBING', 'Plumbing'), ('PHOTOGRAPHER', 'Photographer')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('service_details', models.TextField()),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, max_length=250)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ProffesionalRequestLeads',
            },
        ),
        migrations.CreateModel(
            name='PropertyRequestLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow')], max_length=20)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('max_beds', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('general_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=18)),
                ('parking_choices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=34)),
                ('additional_details', models.TextField()),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent'), ('LEASE', 'Lease')], max_length=20)),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, max_length=250)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PropertyRequestLeads',
            },
        ),
    ]
