# Generated by Django 2.2.12 on 2020-08-10 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Other_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proffesionalrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proffesionalrequest',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Prof_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Prop_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex')], max_length=20),
        ),
    ]
