# Generated by Django 2.2.12 on 2020-11-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequestlead',
            name='claimer',
            field=models.ManyToManyField(blank=True, related_name='Prop_lead_claimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prop_lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Prop_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proffesionalrequestlead',
            name='claimer',
            field=models.ManyToManyField(blank=True, related_name='Prof_lead_claimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proffesionalrequestlead',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prof_lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proffesionalrequestlead',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Prof_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherservicelead',
            name='claimer',
            field=models.ManyToManyField(blank=True, related_name='Other_request_claimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherservicelead',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Other_request_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherservicelead',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Other_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpropertyrequest',
            name='claimer',
            field=models.ManyToManyField(blank=True, related_name='AgProp_lead_claimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpropertyrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AgProp_Lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentpropertyrequest',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='AgProp_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentleadrequest',
            name='claimer',
            field=models.ManyToManyField(blank=True, related_name='Ag_lead_claimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentleadrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ag_lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentleadrequest',
            name='referrer',
            field=models.ManyToManyField(blank=True, related_name='Ag_lead_referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
