# Generated by Django 2.2.12 on 2020-08-10 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0002_auto_20200811_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequestLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('LAND', 'Land'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family')], max_length=20)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('max_beds', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('additional_details', models.TextField()),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent')], max_length=20)),
                ('timeline', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('claimer', models.ManyToManyField(blank=True, related_name='Prop_lead_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prop_lead_owner', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ManyToManyField(blank=True, related_name='Prop_lead_referrer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyRequestLeads',
            },
        ),
        migrations.RenameModel(
            old_name='OtherService',
            new_name='OtherServiceLead',
        ),
        migrations.RenameModel(
            old_name='ProffesionalRequest',
            new_name='ProffesionalRequestLead',
        ),
        migrations.AlterModelOptions(
            name='otherservicelead',
            options={'verbose_name_plural': 'OtherServiceLeads'},
        ),
        migrations.AlterModelOptions(
            name='proffesionalrequestlead',
            options={'verbose_name_plural': 'ProffesionalRequestLeads'},
        ),
        migrations.DeleteModel(
            name='PropertyRequest',
        ),
    ]
