# Generated by Django 2.2.12 on 2020-08-14 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0004_auto_20200813_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservicelead',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proffesionalrequestlead',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='general_features',
            field=models.CharField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=20),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='number_of_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='parking_choices',
            field=models.CharField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='ownership',
            field=models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent'), ('LEASE', 'Lease')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion')], max_length=20),
        ),
        migrations.CreateModel(
            name='AgentPropertyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion')], max_length=20)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('max_beds', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('general_features', models.CharField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=20)),
                ('parking_choices', models.CharField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=20)),
                ('additional_details', models.TextField()),
                ('market_value', models.PositiveIntegerField(default=None)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent'), ('LEASE', 'Lease')], max_length=20)),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('claimer', models.ManyToManyField(blank=True, related_name='AgProp_lead_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AgProp_Lead_owner', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ManyToManyField(blank=True, related_name='AgProp_lead_referrer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgentPropertyRequests',
            },
        ),
        migrations.CreateModel(
            name='AgentLeadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('price_negotiable', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('beds', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('general_features', models.CharField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=20)),
                ('parking_choices', models.CharField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=20)),
                ('additional_details', models.TextField()),
                ('market_value', models.PositiveIntegerField(default=None)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('ownership', models.CharField(choices=[('BUY', 'Buy'), ('RENT', 'Rent'), ('LEASE', 'Lease')], max_length=20)),
                ('timeline', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('claimer', models.ManyToManyField(blank=True, related_name='Ag_lead_claimer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ag_lead_owner', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ManyToManyField(blank=True, related_name='Ag_lead_referrer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgentLeadRequests',
            },
        ),
    ]
