# Generated by Django 2.2.12 on 2020-08-14 23:06

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20200815_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentleadrequest',
            name='location_name',
            field=models.CharField(default=datetime.datetime(2020, 8, 14, 23, 6, 8, 14588, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentpropertyrequest',
            name='location_name',
            field=models.CharField(default=datetime.datetime(2020, 8, 14, 23, 6, 18, 325772, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
    ]
