# Generated by Django 2.2.12 on 2020-08-16 22:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_auto_20200815_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='general_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=18),
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='parking_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=34),
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='general_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SERVICED', 'Serviced')], max_length=18),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='parking_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], max_length=34),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
    ]
