# Generated by Django 2.2.12 on 2020-12-30 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_auto_20201229_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostproposal',
            name='proposal_send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
