# Generated by Django 2.2.12 on 2020-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_auto_20200817_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentpropertyrequest',
            name='location',
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='ownership',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('RENTER', 'Renter'), ('LESSEE', 'Lessee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium')], max_length=20),
        ),
    ]
