# Generated by Django 2.2.12 on 2020-09-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_auto_20200828_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentleadrequest',
            name='profile_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='agentpropertyrequest',
            name='profile_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='otherservicelead',
            name='profile_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='proffesionalrequestlead',
            name='profile_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='propertyrequestlead',
            name='profile_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
    ]
