# Generated by Django 2.2.12 on 2020-09-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20200903_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow')], max_length=20),
        ),
    ]
