# Generated by Django 2.2.12 on 2020-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_auto_20200920_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
    ]
