# Generated by Django 2.2.12 on 2020-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_auto_20200920_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('LAND', 'Land'), ('APARTMENT', 'Apartment')], max_length=20),
        ),
    ]
