# Generated by Django 2.2.12 on 2020-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_auto_20200920_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
    ]
