# Generated by Django 2.2.12 on 2022-01-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0062_auto_20220120_1405'),
        ('markets', '0016_auto_20220127_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(blank=True, related_name='project_question_answer', to='profiles.QuestionOptions')),
                ('project_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_questions', to='markets.ProjectDetails')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_question_answer', to='profiles.Question')),
            ],
            options={
                'verbose_name_plural': 'Project Questions',
            },
        ),
    ]
