# Generated by Django 2.2.12 on 2022-01-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_projectquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquestion',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_question', to='profiles.Question'),
        ),
    ]
