# Generated by Django 2.2.12 on 2020-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0019_auto_20200927_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('LAND', 'Land'), ('MANSION', 'Mansion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('LAND', 'Land'), ('MANSION', 'Mansion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('LAND', 'Land'), ('MANSION', 'Mansion')], max_length=20),
        ),
    ]
