# Generated by Django 2.2.12 on 2022-05-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_auto_20220501_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, null=True)),
                ('item_quantity', models.PositiveIntegerField(blank=True, default=1.0)),
                ('item_price', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_quote_item', to='markets.ProjectQuote')),
            ],
            options={
                'verbose_name_plural': 'Project Quote Item',
            },
        ),
    ]
