# Generated by Django 2.2.12 on 2020-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_auto_20200927_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('DORMITORY', 'Dormitory'), ('LAND', 'Land'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house')], max_length=20),
        ),
    ]
