# Generated by Django 2.2.12 on 2020-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0022_auto_20201003_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('LAND', 'Land'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('LAND', 'Land'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('LAND', 'Land'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
