# Generated by Django 2.2.12 on 2020-11-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0023_auto_20201003_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentleadrequest',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpropertyrequest',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequestlead',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('LAND', 'Land'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], max_length=20),
        ),
    ]
