# Generated by Django 2.2.12 on 2021-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
