# Generated by Django 2.2.12 on 2021-01-08 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_center', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reads',
            field=models.ManyToManyField(blank=True, related_name='blog_post_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
