# Generated by Django 2.2.12 on 2021-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_center', '0004_auto_20210109_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
