# Generated by Django 2.2.12 on 2021-01-09 11:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_center', '0005_auto_20210109_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
