# Generated by Django 2.2.12 on 2020-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201125_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
