# Generated by Django 2.2.12 on 2020-11-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_teammateconnection_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='user',
            new_name='business_profile',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='porfolio_item_type',
            field=models.CharField(choices=[('PROPERTY_MANAGEMENT', 'property management'), ('DESIGN_PROJECT', 'design project'), ('CONSTRUCTION_PROJECT', 'construction project'), ('PROJECT_SALE', 'project sale'), ('PROPERTY_SALE', 'property sale')], max_length=100, null=True),
        ),
    ]
