# Generated by Django 2.2.12 on 2021-01-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201231_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_image', models.ImageField(upload_to='proGroupImages/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='proServiceImages/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='proCategoryImages/')),
                ('professional_group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pro_category_group', to='profiles.ProfessionalGroup')),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='professional_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_business_category', to='profiles.ProfessionalCategory'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='professional_services',
            field=models.ManyToManyField(blank=True, related_name='pro_business_services', to='profiles.ProfessionalService'),
        ),
    ]
