# Generated by Django 2.2.12 on 2021-01-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210102_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='pro_category',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='pro_speciality',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='services',
        ),
    ]
