# Generated by Django 2.2.12 on 2021-02-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_remove_professionalgroup_group_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalgroup',
            old_name='group_image_new',
            new_name='group_image',
        ),
    ]
