# Generated by Django 2.2.12 on 2021-02-11 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20210211_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcategory',
            name='category_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='service_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
