# Generated by Django 2.2.12 on 2021-10-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20211017_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_options',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_option', to='profiles.QuestionOptions'),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='name',
            field=models.CharField(help_text='Option name', max_length=100, null=True),
        ),
    ]
