# Generated by Django 2.2.12 on 2021-10-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20211018_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientanswer',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='proanswer',
            name='text_answer',
        ),
    ]
