# Generated by Django 2.2.12 on 2021-10-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20211018_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientanswer',
            old_name='option_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='proanswer',
            old_name='option_answer',
            new_name='answer',
        ),
    ]
