# Generated by Django 2.2.12 on 2021-10-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_auto_20211018_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='clientanswer',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='option_answer', to='profiles.QuestionOptions'),
        ),
    ]
