# Generated by Django 2.2.12 on 2021-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_auto_20211020_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='azure_identity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
