# Development environment docker compose file
# Version of docker compose to use
version: '3.9'

# services we want to run
services:
  app:
    # image name and a tag name
    image: dev:app
    container_name: rehgien-django-dev
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      # NOTE: Usefull in dev mode only.
      # CONTD: Will allow us to make code changes and have them reflect in or container
      # CONTD: Not required in prod as we won't be making changes to code there
      - ./backend:/app 
    env_file:
      # env. file containing variables to use within this service
      - .env
    command: >
      sh -c " python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
            "
    depends_on:
      - postgres

  postgres:
    restart: always
    # image name and a tag name
    image: dev:postgres
    container_name: rehgien-postgres-dev
    build: ./services/postgres/
    ports:
      - "5432:5432"
    volumes:
      # persist db data beyond the life of the container
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  redis:
    # image name and a tag name
    image: dev:redis
    build: ./services/redis/
    container_name: rehgien-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: