# Production environment docker compose file
# Version of docker compose to use
version: '3.9'

# services we want to run
services:
  app:
    # NOTE: opting for 'always' will always restart service even if you try to stop it
    restart: unless-stopped
    # NOTE: If hosting images on docker hub, ECR or similar,
    # CONTD: you can use the repository URI making it easy to push and pull images.
    # CONTD: (ECR example) image: <myactid>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>:app
    # CONTD: then you can run docker compose -f docker-compose-prod.yml push or pull

    # image name and a tag name
    image: 759451633485.dkr.ecr.us-east-1.amazonaws.com/rehgien:app
    # Any name that can further help ID this container
    container_name: django_container
    build: ./backend
    expose:
      - 9000
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      # persist static files beyond the life of the container
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    env_file:
      # env. file containing variables to use within this service
      - ./.env
    depends_on:
      - postgres

  nginx:
    # NOTE: opting for 'always' will always restart service even if you try to stop it
    restart: unless-stopped
    # NOTE: If hosting images on docker hub, ECR or similar,
    # CONTD: you can use the repository URI making it easy to push and pull images.
    # CONTD: (ECR example) image: <myactid>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>:nginx
    # CONTD: then you can run docker compose -f docker-compose-prod.yml push or pull

    # image name and a tag name
    image: 759451633485.dkr.ecr.us-east-1.amazonaws.com/rehgien:nginx
    # Any name that can further help ID this container
    container_name: nginx-prod
    build: ./services/nginx/
    ports:
      - "80:8000"
      - 443:443
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
      # switch between dev (no ssl) and production (with ssl) nginx configs files
      - ./services/nginx/production:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    links:
      - app:app
    depends_on:
      - app

  postgres:
    # NOTE: opting for 'always' will always restart service even if you try to stop it
    restart: unless-stopped
    # NOTE: If hosting images on docker hub, ECR or similar,
    # CONTD: you can use the repository URI making it easy to push and pull images.
    # CONTD: (ECR example) image: <myactid>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>:postgres
    # CONTD: then you can run docker compose -f docker-compose-prod.yml push or pull

    # image name and a tag name
    image: 759451633485.dkr.ecr.us-east-1.amazonaws.com/rehgien:postgres
    # Any name that can further help ID this container
    container_name: postgres-prod
    build: ./services/postgres/
    ports:
      - "5432:5432"
    volumes:
      # NOTE: Don't manage db in the container. Its easy to wipe data unknowingly.
      # CONTD: eg. you might need to run docker compose -f docker-compose-prod.yml down -v 
      # CONTD: an action that will wipe  all services volumes incl. db data.
      # CONTD: Use RDS or similar
      
      # persist db data beyond the life of the container
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  redis:
    # NOTE: opting for 'always' will always restart service even if you try to stop it
    restart: unless-stopped
    # NOTE: If hosting images on docker hub, ECR or similar,
    # CONTD: you can use the repository URI making it easy to push and pull images.
    # CONTD: (ECR example) image: <myactid>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>:redis
    # CONTD: then you can run docker compose -f docker-compose-prod.yml push or pull

    # image name and a tag name
    image: 759451633485.dkr.ecr.us-east-1.amazonaws.com/rehgien:redis
    build: ./services/redis/
    container_name: redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  static_volume:
  media_volume:
  pgdata:
  redisdata: