# Generated by Django 2.2.12 on 2020-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_auto_20201226_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='project_duration',
            field=models.CharField(choices=[('1', '<span>less than a week</span>'), ('2', '<span>less than 1 month</span>'), ('3', '<span>1 to 3 months</span>'), ('4', '<span>3 to 6 months</span>'), ('5', '<span>more than 6 months</span>')], max_length=20),
        ),
    ]
