# Generated by Django 2.2.12 on 2022-01-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_kenyatown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0062_auto_20220120_1405'),
        ('markets', '0011_auto_20210119_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message', models.TextField()),
                ('pro_response_state', models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=20, null=True)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('pro_contacted', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_post_responder', to=settings.AUTH_USER_MODEL)),
                ('requested_service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_service', to='profiles.ProfessionalService')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('negotiable', models.BooleanField(blank=True, default=False, null=True)),
                ('quote_send_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_quote', to='markets.Project')),
                ('quote_sender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_quote_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Quote',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(blank=True, related_name='project_qestion_option_answer', to='profiles.QuestionOptions')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_of_project', to='location.KenyaTown')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='markets.Project')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_question_answer', to='profiles.Question')),
            ],
            options={
                'verbose_name_plural': 'Project Details',
            },
        ),
    ]
