# Generated by Django 2.2.12 on 2022-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0021_projectquoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='billing_model',
            field=models.CharField(choices=[('FLAT', 'flat'), ('HOURLY', 'hourly'), ('RECURRING', 'recurring')], default='FLAT', max_length=20, null=True),
        ),
    ]
