# Generated by Django 2.2.12 on 2022-07-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0063_useraddress'),
        ('markets', '0022_projectquote_billing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery_address', to='profiles.UserAddress'),
        ),
        migrations.AddField(
            model_name='project',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='profiles.ProfessionalService'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on delivery'), ('REHGIEN_PAY', 'Rehgien pay')], default='CASH', max_length=25, null=True),
        ),
    ]
