# Generated by Django 2.1.3 on 2019-07-22 13:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('type', models.CharField(choices=[('OTH', 'Other'), ('BUNG', 'Bungalow'), ('TERRA', 'Terraced house'), ('MANS', 'Mansion'), ('COND', 'Condominium'), ('DORM', 'Dormitory'), ('DUPL', 'Duplex'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('APAR', 'Apartment')], default='APART', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('virtual_tour_url', models.CharField(default=None, max_length=500)),
                ('location_name', models.CharField(default=None, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('thumb', models.ImageField(default=None, upload_to='')),
                ('bathrooms', models.IntegerField(blank=True, default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('total_rooms', models.IntegerField(default=1)),
                ('floor_number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('lot_size', models.FloatField(blank=True, default=1.0)),
                ('lot_size_measurement_unit', models.CharField(choices=[('SQft', 'SqFt'), ('Acres', 'Acre(s)'), ('SQm', 'SqM')], default='Acres', max_length=10)),
                ('number_of_units', models.IntegerField(default=1)),
                ('number_of_stories', models.IntegerField(default=0)),
                ('parking_spaces', models.IntegerField(default=1)),
                ('year_built', models.IntegerField(default=2000)),
                ('remodel_year', models.IntegerField(blank=True, null=True)),
                ('garage_sqm', models.IntegerField(blank=True, default=1)),
                ('open_house', models.DateTimeField(blank=True)),
                ('appliances', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DISH', 'Dishwasher'), ('GARB', 'Garbage disposal'), ('OVEN', 'Oven'), ('REFRIG', 'Refrigerator'), ('NON', 'None')], default=None, max_length=25)),
                ('basement', models.CharField(blank=True, choices=[('FINI', 'Finished'), ('UNFI', 'Unfinished'), ('PART', 'Partially finished'), ('NON', 'None')], default=None, max_length=10)),
                ('floor_covering', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carpet'), ('CONC', 'Concrete'), ('HARD', 'Hardwood'), ('TILE', 'Tile'), ('SOFT', 'SoftWood'), ('OTH', 'Other')], default=None, max_length=28)),
                ('rooms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BREA', 'BreakFast nook'), ('DINI', 'Dining room'), ('FAMI', 'Family room'), ('LIBR', 'Library'), ('MAST', 'Master bath'), ('MUDR', 'Mud room'), ('OF', 'Office'), ('PANT', 'Pantry'), ('RECR', 'Recreation room'), ('WORK', 'Workshop'), ('So/AR', 'Solarium/Atrium'), ('SUNR', 'Sun room'), ('WALK', 'walk-in-closet')], default=None, max_length=63)),
                ('indoor_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ATTI', 'Attic'), ('CEIL', 'Ceiling fans'), ('DOUB', 'Double pane windows'), ('FIRE', 'Fireplace'), ('SECU', 'Security system'), ('SKYL', 'Skylights'), ('VAUL', 'Vaulted ceiling')], default=None, max_length=34)),
                ('cooling_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CENT', 'Central'), ('EVAP', 'Evaporative'), ('GEOT', 'Geothermal'), ('REFR', 'Refrigeration'), ('SOLA', 'Solar'), ('WALL', 'Wall'), ('OTHE', 'Other'), ('NON', 'None')], default=None, max_length=38)),
                ('heating_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASE', 'Baseboard'), ('FORC', 'Forced air'), ('GEOT', 'Geothermal'), ('HEAT', 'Heat pump'), ('RADI', 'Radiant'), ('STOV', 'Stove'), ('WALL', 'Wall'), ('OTH', 'Other')], default=None, max_length=38)),
                ('heating_fuel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('COAL', 'Coal'), ('ELEC', 'Electric'), ('GAS', 'Gas'), ('OIL', 'Oil'), ('PR/BU', 'Propane/Butane'), ('SOLA', 'Solar'), ('WO/PE', 'Wood/Pelet'), ('OTH', 'Other'), ('NON', 'None')], default=None, max_length=42)),
                ('building_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASK', 'Basketball court'), ('CONT', 'Controlled access'), ('DISA', 'Disabled access'), ('DOOR', 'Doorman'), ('ELEV', 'Elevator'), ('FITN', 'Fitness Center'), ('GATE', 'Gated entry'), ('NEAR', 'Near Transportation'), ('SPOR', 'Sports court')], default=None, max_length=44)),
                ('exterior', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BRIC', 'Brick'), ('CE/CO', 'Cement/Concrete'), ('STON', 'Stone'), ('VINY', 'Vinyl'), ('WOOD', 'Wood'), ('OTH', 'Other')], default=None, max_length=29)),
                ('outdoor_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BALC', 'Balcony'), ('FENC', 'Fenced yard'), ('GARD', 'Garden'), ('GREEN', 'Greenhouse'), ('LAWN', 'Lawn'), ('POND', 'Pond'), ('POOL', 'Pool'), ('SAUN', 'Sauna'), ('SPRI', 'Sprinkler system'), ('wATER', 'Waterfront')], default=None, max_length=51)),
                ('parking', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], default=None, max_length=34)),
                ('roof', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ASPH', 'Asphalt'), ('TILE', 'Tile'), ('SLAT', 'Slate'), ('OTH', 'Other')], default=None, max_length=18)),
                ('view', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('TERR', 'Territorial'), ('MOUN', 'Mountain'), ('WATE', 'Water'), ('PARK', 'Park'), ('NON', 'None')], default=None, max_length=28)),
                ('related_website', models.CharField(default=None, max_length=100)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyForSale',
            },
        ),
        migrations.CreateModel(
            name='PropertyForSaleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.PropertyForSale')),
            ],
            options={
                'verbose_name_plural': 'PropertyForSaleImages',
            },
        ),
        migrations.CreateModel(
            name='PropertyForSaleVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.PropertyForSale')),
            ],
            options={
                'verbose_name_plural': 'PropertyForSaleVideos',
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OTH', 'Other'), ('BUNG', 'Bungalow'), ('TERRA', 'Terraced house'), ('MANS', 'Mansion'), ('COND', 'Condominium'), ('DORM', 'Dormitory'), ('DUPL', 'Duplex'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('APAR', 'Apartment')], default='APAR', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('virtual_tour_url', models.CharField(default=None, max_length=500)),
                ('location_name', models.CharField(default='Nairobi', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('thumb', models.ImageField(default=None, upload_to='')),
                ('bathrooms', models.IntegerField(blank=True, default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('total_rooms', models.IntegerField(default=1)),
                ('floor_number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('floor_area', models.FloatField(blank=True, default=1.0)),
                ('floor_area_measurement_unit', models.CharField(choices=[('SQft', 'SqFt'), ('SQm', 'SqM')], default='Acres', max_length=10)),
                ('number_of_units', models.IntegerField(default=1)),
                ('number_of_stories', models.IntegerField(default=0)),
                ('parking_spaces', models.IntegerField(default=1)),
                ('year_built', models.IntegerField(default=2000)),
                ('remodel_year', models.IntegerField(blank=True, null=True)),
                ('open_house', models.DateTimeField(blank=True)),
                ('appliances', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DISH', 'Dishwasher'), ('GARB', 'Garbage disposal'), ('OVEN', 'Oven'), ('REFRIG', 'Refrigerator'), ('NON', 'None')], default=None, max_length=25)),
                ('basement', models.CharField(blank=True, choices=[('FINI', 'Finished'), ('UNFI', 'Unfinished'), ('PART', 'Partially finished'), ('NON', 'None')], default=None, max_length=10)),
                ('floor_covering', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carpet'), ('CONC', 'Concrete'), ('HARD', 'Hardwood'), ('TILE', 'Tile'), ('SOFT', 'SoftWood'), ('OTH', 'Other')], default=None, max_length=28)),
                ('rooms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BREA', 'BreakFast nook'), ('DINI', 'Dining room'), ('FAMI', 'Family room'), ('LIBR', 'Library'), ('MAST', 'Master bath'), ('MUDR', 'Mud room'), ('OF', 'Office'), ('PANT', 'Pantry'), ('RECR', 'Recreation room'), ('WORK', 'Workshop'), ('So/AR', 'Solarium/Atrium'), ('SUNR', 'Sun room'), ('WALK', 'walk-in-closet')], default=None, max_length=63)),
                ('indoor_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ATTI', 'Attic'), ('CEIL', 'Ceiling fans'), ('DOUB', 'Double pane windows'), ('FIRE', 'Fireplace'), ('SECU', 'Security system'), ('SKYL', 'Skylights'), ('VAUL', 'Vaulted ceiling')], default=None, max_length=34)),
                ('cooling_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CENT', 'Central'), ('EVAP', 'Evaporative'), ('GEOT', 'Geothermal'), ('REFR', 'Refrigeration'), ('SOLA', 'Solar'), ('WALL', 'Wall'), ('OTHE', 'Other'), ('NON', 'None')], default=None, max_length=38)),
                ('heating_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASE', 'Baseboard'), ('FORC', 'Forced air'), ('GEOT', 'Geothermal'), ('HEAT', 'Heat pump'), ('RADI', 'Radiant'), ('STOV', 'Stove'), ('WALL', 'Wall'), ('OTH', 'Other')], default=None, max_length=38)),
                ('heating_fuel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('COAL', 'Coal'), ('ELEC', 'Electric'), ('GAS', 'Gas'), ('OIL', 'Oil'), ('PR/BU', 'Propane/Butane'), ('SOLA', 'Solar'), ('WO/PE', 'Wood/Pelet'), ('OTH', 'Other'), ('NON', 'None')], default=None, max_length=42)),
                ('building_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASK', 'Basketball court'), ('CONT', 'Controlled access'), ('DISA', 'Disabled access'), ('DOOR', 'Doorman'), ('ELEV', 'Elevator'), ('FITN', 'Fitness Center'), ('GATE', 'Gated entry'), ('NEAR', 'Near Transportation'), ('SPOR', 'Sports court')], default=None, max_length=44)),
                ('exterior', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BRIC', 'Brick'), ('CE/CO', 'Cement/Concrete'), ('STON', 'Stone'), ('VINY', 'Vinyl'), ('WOOD', 'Wood'), ('OTH', 'Other')], default=None, max_length=29)),
                ('outdoor_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BALC', 'Balcony'), ('FENC', 'Fenced yard'), ('GARD', 'Garden'), ('GREEN', 'Greenhouse'), ('LAWN', 'Lawn'), ('POND', 'Pond'), ('POOL', 'Pool'), ('SAUN', 'Sauna'), ('SPRI', 'Sprinkler system'), ('wATER', 'Waterfront')], default=None, max_length=51)),
                ('parking', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], default=None, max_length=34)),
                ('roof', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ASPH', 'Asphalt'), ('TILE', 'Tile'), ('SLAT', 'Slate'), ('OTH', 'Other')], default=None, max_length=18)),
                ('view', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('TERR', 'Territorial'), ('MOUN', 'Mountain'), ('WATE', 'Water'), ('PARK', 'Park'), ('NON', 'None')], default=None, max_length=28)),
                ('related_website', models.CharField(default=None, max_length=100)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RentalProperty',
            },
        ),
    ]
