# Generated by Django 2.2.12 on 2020-11-21 15:58

import cloudinary.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import listings.validators
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(db_index=True, default=None, max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('virtual_tour_url', models.CharField(default=None, max_length=500)),
                ('location_name', models.CharField(default=None, max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('description', models.TextField()),
                ('floor_area', models.PositiveIntegerField(blank=True, default=1.0)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('related_website', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('listing_type', models.CharField(choices=[('for_sale', 'for_sale'), ('for_rent', 'for_rent')], default='for_sale', max_length=20)),
                ('property_category', models.CharField(choices=[('homes', 'homes')], default='homes', max_length=20)),
                ('type', models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20)),
                ('bathrooms', models.PositiveIntegerField(blank=True, default=1)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('floor_number', models.PositiveIntegerField(default=0)),
                ('number_of_stories', models.PositiveIntegerField(default=0)),
                ('parking_spaces', models.PositiveIntegerField(default=1)),
                ('year_built', models.PositiveIntegerField(default=2000)),
                ('remodel_year', models.PositiveIntegerField(blank=True, null=True)),
                ('garage_sqm', models.PositiveIntegerField(blank=True, default=1)),
                ('appliances', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DISH', 'Dishwasher'), ('GARB', 'Garbage disposal'), ('OVEN', 'Oven'), ('REFRIG', 'Refrigerator'), ('NON', 'None')], default=None, max_length=25)),
                ('basement', models.CharField(blank=True, choices=[('FINI', 'Finished'), ('UNFI', 'Unfinished'), ('PART', 'Partially finished'), ('NON', 'None')], default=None, max_length=10)),
                ('floor_covering', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carpet'), ('CONC', 'Concrete'), ('HARD', 'Hardwood'), ('TILE', 'Tile'), ('SOFT', 'SoftWood'), ('OTH', 'Other')], default=None, max_length=28)),
                ('rooms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BREA', 'BreakFast nook'), ('DINI', 'Dining room'), ('FAMI', 'Family room'), ('LIBR', 'Library'), ('MAST', 'Master bath'), ('MUDR', 'Mud room'), ('OF', 'Office'), ('PANT', 'Pantry'), ('RECR', 'Recreation room'), ('WORK', 'Workshop'), ('So/AR', 'Solarium/Atrium'), ('SUNR', 'Sun room'), ('WALK', 'walk-in-closet')], default=None, max_length=63)),
                ('indoor_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ATTI', 'Attic'), ('CEIL', 'Ceiling fans'), ('DOUB', 'Double pane windows'), ('FIRE', 'Fireplace'), ('SECU', 'Security system'), ('SKYL', 'Skylights'), ('VAUL', 'Vaulted ceiling')], default=None, max_length=34)),
                ('cooling_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CENT', 'Central'), ('EVAP', 'Evaporative'), ('GEOT', 'Geothermal'), ('REFR', 'Refrigeration'), ('SOLA', 'Solar'), ('WALL', 'Wall'), ('OTHE', 'Other'), ('NON', 'None')], default=None, max_length=38)),
                ('heating_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASE', 'Baseboard'), ('FORC', 'Forced air'), ('GEOT', 'Geothermal'), ('HEAT', 'Heat pump'), ('RADI', 'Radiant'), ('STOV', 'Stove'), ('WALL', 'Wall'), ('OTH', 'Other')], default=None, max_length=38)),
                ('heating_fuel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('COAL', 'Coal'), ('ELEC', 'Electric'), ('GAS', 'Gas'), ('OIL', 'Oil'), ('PR/BU', 'Propane/Butane'), ('SOLA', 'Solar'), ('WO/PE', 'Wood/Pelet'), ('OTH', 'Other'), ('NON', 'None')], default=None, max_length=42)),
                ('building_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BASK', 'Basketball court'), ('CONT', 'Controlled access'), ('DISA', 'Disabled access'), ('DOOR', 'Doorman'), ('ELEV', 'Elevator'), ('FITN', 'Fitness Center'), ('GATE', 'Gated entry'), ('NEAR', 'Near Transportation'), ('SPOR', 'Sports court')], default=None, max_length=44)),
                ('exterior', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BRIC', 'Brick'), ('CE/CO', 'Cement/Concrete'), ('STON', 'Stone'), ('VINY', 'Vinyl'), ('WOOD', 'Wood'), ('OTH', 'Other')], default=None, max_length=29)),
                ('outdoor_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BALC', 'Balcony'), ('FENC', 'Fenced yard'), ('GARD', 'Garden'), ('GREEN', 'Greenhouse'), ('LAWN', 'Lawn'), ('POND', 'Pond'), ('POOL', 'Pool'), ('SAUN', 'Sauna'), ('SPRI', 'Sprinkler system'), ('wATER', 'Waterfront')], default=None, max_length=51)),
                ('parking', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARP', 'Carport'), ('GATTACH', 'Garage-Attached'), ('GDETACH', 'Garage-Detached'), ('OFFS', 'Off-street'), ('ONST', 'On-street'), ('NON', 'None')], default=None, max_length=34)),
                ('roof', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ASPH', 'Asphalt'), ('TILE', 'Tile'), ('SLAT', 'Slate'), ('OTH', 'Other')], default=None, max_length=18)),
                ('view', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('TERR', 'Territorial'), ('MOUN', 'Mountain'), ('WATE', 'Water'), ('PARK', 'Park'), ('NON', 'None')], default=None, max_length=28)),
            ],
            options={
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('bungalow', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('condominium', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('dormitory', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('duplex', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('mansion', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('single_family', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('terraced_house', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('townhouse', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
                ('other', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
            ],
            options={
                'verbose_name_plural': 'PropertyTypeImages',
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[listings.validators.validate_video_extension], verbose_name='video')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_video', to='listings.Home')),
            ],
            options={
                'verbose_name_plural': 'PropertyVideo',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photo')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_photos', to='listings.Home')),
            ],
            options={
                'verbose_name_plural': 'PropertyPhoto',
            },
        ),
    ]
