# Generated by Django 2.2.12 on 2020-11-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings_home_owner_related', related_query_name='listings_home_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='listings_home_saves_related', related_query_name='listings_home_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
