# Generated by Django 2.1.3 on 2020-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
