# Generated by Django 2.1.3 on 2019-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforsale',
            name='portfolio',
            field=models.CharField(default='samo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DUPL', 'Duplex'), ('DORM', 'Dormitory'), ('BUNG', 'Bungalow'), ('OTH', 'Other'), ('TERRA', 'Terraced house'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('APAR', 'Apartment'), ('SING', 'Single family'), ('COND', 'Condominium')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DUPL', 'Duplex'), ('DORM', 'Dormitory'), ('BUNG', 'Bungalow'), ('OTH', 'Other'), ('TERRA', 'Terraced house'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('APAR', 'Apartment'), ('SING', 'Single family'), ('COND', 'Condominium')], default='APAR', max_length=20),
        ),
    ]
