# Generated by Django 2.1.3 on 2019-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190722_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyforsale',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('OTH', 'Other'), ('APAR', 'Apartment'), ('MANS', 'Mansion'), ('TERRA', 'Terraced house'), ('SING', 'Single family'), ('BUNG', 'Bungalow'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('DUPL', 'Duplex')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('OTH', 'Other'), ('APAR', 'Apartment'), ('MANS', 'Mansion'), ('TERRA', 'Terraced house'), ('SING', 'Single family'), ('BUNG', 'Bungalow'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('DUPL', 'Duplex')], default='APAR', max_length=20),
        ),
    ]
