# Generated by Django 2.2.12 on 2020-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200521_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ImageField(upload_to='categoryImages/')),
                ('bungalow', models.ImageField(upload_to='categoryImages/')),
                ('condominium', models.ImageField(upload_to='categoryImages/')),
                ('dormitory', models.ImageField(upload_to='categoryImages/')),
                ('duplex', models.ImageField(upload_to='categoryImages/')),
                ('mansion', models.ImageField(upload_to='categoryImages/')),
                ('single_family', models.ImageField(upload_to='categoryImages/')),
                ('terraced_house', models.ImageField(upload_to='categoryImages/')),
                ('townhouse', models.ImageField(upload_to='categoryImages/')),
                ('other', models.ImageField(upload_to='categoryImages/')),
            ],
            options={
                'verbose_name_plural': 'PropertyTypeImages',
            },
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
