# Generated by Django 2.1.3 on 2019-07-23 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_auto_20190722_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforsale',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='slug',
            field=models.SlugField(default='juja-south-estate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DORM', 'Dormitory'), ('TOWN', 'Townhouse'), ('TERRA', 'Terraced house'), ('BUNG', 'Bungalow'), ('OTH', 'Other'), ('SING', 'Single family'), ('MANS', 'Mansion'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('COND', 'Condominium')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORM', 'Dormitory'), ('TOWN', 'Townhouse'), ('TERRA', 'Terraced house'), ('BUNG', 'Bungalow'), ('OTH', 'Other'), ('SING', 'Single family'), ('MANS', 'Mansion'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('COND', 'Condominium')], default='APAR', max_length=20),
        ),
    ]
