# Generated by Django 2.2.12 on 2020-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200521_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
