# Generated by Django 2.1.3 on 2020-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200319_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
