# Generated by Django 2.2.12 on 2020-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201201_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='property_category',
            field=models.CharField(choices=[('HOMES', 'homes')], default='HOMES', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
