# Generated by Django 2.1.3 on 2020-03-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200319_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalimages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.RentalProperty'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalvideos',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.RentalProperty'),
        ),
    ]
