# Generated by Django 2.2.12 on 2020-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200521_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='apartment',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='bungalow',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='condominium',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='dormitory',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='duplex',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='mansion',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='other',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='single_family',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='terraced_house',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='propertytypeimage',
            name='townhouse',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
