# Generated by Django 2.1.3 on 2019-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190723_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('COND', 'Condominium'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('APAR', 'Apartment'), ('MANS', 'Mansion'), ('DUPL', 'Duplex'), ('OTH', 'Other'), ('DORM', 'Dormitory'), ('BUNG', 'Bungalow')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('COND', 'Condominium'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('APAR', 'Apartment'), ('MANS', 'Mansion'), ('DUPL', 'Duplex'), ('OTH', 'Other'), ('DORM', 'Dormitory'), ('BUNG', 'Bungalow')], default='APAR', max_length=20),
        ),
    ]
