# Generated by Django 2.2.12 on 2020-09-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200521_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
    ]
