# Generated by Django 2.1.3 on 2019-07-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190724_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'RentalImages',
            },
        ),
        migrations.CreateModel(
            name='RentalVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'RentalVideos',
            },
        ),
        migrations.RenameField(
            model_name='propertyforsale',
            old_name='lot_size',
            new_name='floor_or_lot_size',
        ),
        migrations.RenameField(
            model_name='propertyforsale',
            old_name='lot_size_measurement_unit',
            new_name='size_units',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='slug',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='floor_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='garage_sqm',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='number_of_stories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='number_of_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='remodel_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('COND', 'Condominium'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('DORM', 'Dormitory'), ('SING', 'Single family'), ('DUPL', 'Duplex'), ('OTH', 'Other'), ('MANS', 'Mansion'), ('BUNG', 'Bungalow')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='year_built',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='floor_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='number_of_stories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='number_of_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='remodel_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('COND', 'Condominium'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('DORM', 'Dormitory'), ('SING', 'Single family'), ('DUPL', 'Duplex'), ('OTH', 'Other'), ('MANS', 'Mansion'), ('BUNG', 'Bungalow')], default='APAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='year_built',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='rentalvideos',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.RentalProperty'),
        ),
        migrations.AddField(
            model_name='rentalimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.RentalProperty'),
        ),
    ]
