# Generated by Django 2.1.3 on 2020-04-10 18:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200320_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforsale',
            name='prop_images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsaleimages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.PropertyForSale'),
        ),
        migrations.AlterField(
            model_name='propertyforsalevideos',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.PropertyForSale'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
