# Generated by Django 2.1.3 on 2020-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200410_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
