# Generated by Django 2.2.12 on 2020-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200920_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
