# Generated by Django 2.1.3 on 2019-07-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190726_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('DORM', 'Dormitory'), ('COND', 'Condominium'), ('DUPL', 'Duplex'), ('BUNG', 'Bungalow'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('OTH', 'Other'), ('SING', 'Single family'), ('APAR', 'Apartment')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('DORM', 'Dormitory'), ('COND', 'Condominium'), ('DUPL', 'Duplex'), ('BUNG', 'Bungalow'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('OTH', 'Other'), ('SING', 'Single family'), ('APAR', 'Apartment')], default='APAR', max_length=20),
        ),
    ]
