# Generated by Django 2.2.12 on 2020-12-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20201203_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='property_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
    ]
