# Generated by Django 2.2.12 on 2020-12-04 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_auto_20201204_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='property_views',
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('has_viewed', models.BooleanField(blank=True, default=False, null=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_interactions', to='listings.Home')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertyInteractions',
            },
        ),
    ]
