# Generated by Django 2.1.3 on 2020-04-10 20:34

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200410_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyforsale',
            name='prop_images',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsaleimages',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
