# Generated by Django 2.1.3 on 2019-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190726_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalproperty',
            old_name='floor_area_measurement_unit',
            new_name='size_units',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='floor_or_lot_size',
            field=models.PositiveIntegerField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('OTH', 'Other'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('BUNG', 'Bungalow'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('MANS', 'Mansion')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='floor_area',
            field=models.PositiveIntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('OTH', 'Other'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('BUNG', 'Bungalow'), ('SING', 'Single family'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('MANS', 'Mansion')], default='APAR', max_length=20),
        ),
    ]
