# Generated by Django 2.2.12 on 2020-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200920_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
    ]
