# Generated by Django 2.1.3 on 2020-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200410_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
