# Generated by Django 2.2.12 on 2020-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200920_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
