# Generated by Django 2.1.3 on 2019-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190726_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforsale',
            old_name='floor_or_lot_size',
            new_name='floor_area',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='location_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='size_units',
            field=models.CharField(choices=[('SQft', 'SqFt'), ('SQm', 'SqM')], default='Acres', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('SING', 'Single family'), ('OTH', 'Other'), ('APAR', 'Apartment'), ('TERRA', 'Terraced house'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DUPL', 'Duplex')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('COND', 'Condominium'), ('SING', 'Single family'), ('OTH', 'Other'), ('APAR', 'Apartment'), ('TERRA', 'Terraced house'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DUPL', 'Duplex')], default='APAR', max_length=20),
        ),
    ]
