# Generated by Django 2.2.12 on 2020-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20201204_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinteraction',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
    ]
