# Generated by Django 2.1.3 on 2019-07-29 14:27

from django.db import migrations, models
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190729_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('BUNG', 'Bungalow'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('OTH', 'Other'), ('COND', 'Condominium'), ('SING', 'Single family'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('TERRA', 'Terraced house')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsalevideos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[listings.validators.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('BUNG', 'Bungalow'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DORM', 'Dormitory'), ('OTH', 'Other'), ('COND', 'Condominium'), ('SING', 'Single family'), ('APAR', 'Apartment'), ('DUPL', 'Duplex'), ('TERRA', 'Terraced house')], default='APAR', max_length=20),
        ),
    ]
