# Generated by Django 2.1.3 on 2020-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200410_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
    ]
