# Generated by Django 2.1.3 on 2020-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200411_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
    ]
