# Generated by Django 2.1.3 on 2019-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190729_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('OTH', 'Other'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('APAR', 'Apartment'), ('TERRA', 'Terraced house'), ('SING', 'Single family'), ('COND', 'Condominium'), ('DUPL', 'Duplex'), ('MANS', 'Mansion')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('OTH', 'Other'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('APAR', 'Apartment'), ('TERRA', 'Terraced house'), ('SING', 'Single family'), ('COND', 'Condominium'), ('DUPL', 'Duplex'), ('MANS', 'Mansion')], default='APAR', max_length=20),
        ),
    ]
