# Generated by Django 2.2.12 on 2020-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200920_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
