# Generated by Django 2.1.3 on 2019-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190730_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='location_name',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('DUPL', 'Duplex'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('COND', 'Condominium'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('MANS', 'Mansion'), ('SING', 'Single family'), ('OTH', 'Other')], db_index=True, default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWN', 'Townhouse'), ('DUPL', 'Duplex'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('COND', 'Condominium'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('MANS', 'Mansion'), ('SING', 'Single family'), ('OTH', 'Other')], default='APAR', max_length=20),
        ),
    ]
