# Generated by Django 2.2.12 on 2020-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20201204_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinteraction',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
