# Generated by Django 2.2.12 on 2020-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200921_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
