# Generated by Django 2.2.12 on 2020-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200411_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
    ]
