# Generated by Django 2.1.3 on 2019-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190801_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='location_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DUPL', 'Duplex'), ('COND', 'Condominium'), ('APAR', 'Apartment'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('SING', 'Single family'), ('OTH', 'Other')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRA', 'Terraced house'), ('MANS', 'Mansion'), ('TOWN', 'Townhouse'), ('DUPL', 'Duplex'), ('COND', 'Condominium'), ('APAR', 'Apartment'), ('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('SING', 'Single family'), ('OTH', 'Other')], default='APAR', max_length=20),
        ),
    ]
