# Generated by Django 2.2.12 on 2020-12-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20201204_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active_untill',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='home',
            name='deal_closed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='final_closing_offer',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
