# Generated by Django 2.1.3 on 2019-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190801_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('SING', 'Single family'), ('OTH', 'Other'), ('DUPL', 'Duplex'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('COND', 'Condominium')], default='APART', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('BUNG', 'Bungalow'), ('DORM', 'Dormitory'), ('TERRA', 'Terraced house'), ('APAR', 'Apartment'), ('SING', 'Single family'), ('OTH', 'Other'), ('DUPL', 'Duplex'), ('TOWN', 'Townhouse'), ('MANS', 'Mansion'), ('COND', 'Condominium')], default='APAR', max_length=20),
        ),
    ]
