# Generated by Django 2.2.12 on 2020-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200411_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
    ]
