# Generated by Django 2.2.12 on 2020-12-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20201204_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='active_untill',
        ),
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
