# Generated by Django 2.2.12 on 2020-04-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200416_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILIY', 'Single family'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
