# Generated by Django 2.2.12 on 2020-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200927_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
