# Generated by Django 2.1.3 on 2019-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190804_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILIY', 'Single family'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILIY', 'Single family'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
