# Generated by Django 2.1.3 on 2019-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20190915_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='open_house',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='open_house',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
