# Generated by Django 2.2.12 on 2020-04-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200416_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('SINGLEFAMILIY', 'Single family'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium')], default='APARTMENT', max_length=20),
        ),
    ]
