# Generated by Django 2.1.3 on 2019-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190922_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyforsale',
            name='open_house',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='open_house',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('SINGLEFAMILIY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
