# Generated by Django 2.2.12 on 2020-12-05 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20201205_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='open_house',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='deal_closed',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'No')], default='YES', max_length=3),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
