# Generated by Django 2.1.3 on 2019-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20190922_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforsale',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='rentalproperty',
            old_name='name',
            new_name='property_name',
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILIY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILIY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
