# Generated by Django 2.2.12 on 2020-11-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20201003_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
