# Generated by Django 2.1.3 on 2019-09-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20190929_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILIY', 'Single family')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILIY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
