# Generated by Django 2.2.12 on 2020-12-06 11:54

import cloudinary.models
from django.db import migrations, models
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20201206_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[listings.validators.validate_video_extension], verbose_name='video'),
        ),
    ]
