# Generated by Django 2.1.3 on 2020-03-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20190929_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSaleCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILIY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='type',
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILIY', 'Single family'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='forsalecategories',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='listings.PropertyForSale'),
        ),
    ]
