# Generated by Django 2.1.3 on 2020-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20200303_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forsalecategories',
            name='property',
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('SINGLEFAMILIY', 'Single family'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
        migrations.DeleteModel(
            name='ForSaleCategories',
        ),
    ]
