# Generated by Django 2.2.12 on 2020-12-07 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0020_auto_20201206_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyopenhouse',
            name='reminder_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='open_house_reminder_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
