# Generated by Django 2.2.12 on 2020-12-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0022_auto_20201209_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.URLField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_search', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
