# Generated by Django 2.2.12 on 2021-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20210102_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
