# Generated by Django 2.2.12 on 2021-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20210102_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
