# Generated by Django 2.2.12 on 2021-01-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20210102_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
