# Generated by Django 2.2.12 on 2021-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20210102_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
