# Generated by Django 2.2.12 on 2021-01-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_auto_20210102_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
