# Generated by Django 2.2.12 on 2021-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_auto_20210102_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
