# Generated by Django 2.2.12 on 2021-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_auto_20210103_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
    ]
