# Generated by Django 2.2.12 on 2021-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20210103_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
    ]
