# Generated by Django 2.2.12 on 2021-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_auto_20210108_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
