# Generated by Django 2.2.12 on 2021-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_auto_20210108_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
    ]
