# Generated by Django 2.2.12 on 2021-01-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_auto_20210108_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
