# Generated by Django 2.2.12 on 2021-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_auto_20210109_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
