# Generated by Django 2.2.12 on 2021-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_auto_20210109_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('MANSION', 'Mansion')], default='APARTMENT', max_length=20),
        ),
    ]
