# Generated by Django 2.2.12 on 2021-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_auto_20210118_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
