# Generated by Django 2.2.12 on 2021-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_auto_20210119_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium')], default='APARTMENT', max_length=20),
        ),
    ]
