# Generated by Django 2.2.12 on 2021-02-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_auto_20210224_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='location_name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
