# Generated by Django 2.2.12 on 2021-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_auto_20210224_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='related_website',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
