# Generated by Django 2.2.12 on 2020-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='listing_type',
            field=models.CharField(choices=[('FOR_SALE', 'for sale'), ('FOR_RENT', 'for rent')], default='FOR_SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family')], default='APARTMENT', max_length=20),
        ),
    ]
