# Generated by Django 2.2.12 on 2020-12-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20201205_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='open_house',
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('TOWNHOUSE', 'Townhouse'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow')], default='APARTMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyOpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_openhouse', to='listings.Home')),
            ],
            options={
                'verbose_name_plural': 'PropertyOpenHouses',
            },
        ),
    ]
