# Generated by Django 2.2.12 on 2020-12-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20201207_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('OTHER', 'Other'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinteraction',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_property_interation', to=settings.AUTH_USER_MODEL),
        ),
    ]
