# Generated by Django 2.2.12 on 2021-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20201231_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('APARTMENT', 'Apartment'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
