# Generated by Django 2.2.12 on 2021-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20210102_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TERRACED', 'Terraced house'), ('BUNGALOW', 'Bungalow'), ('MANSION', 'Mansion'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
