# Generated by Django 2.2.12 on 2021-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_auto_20210108_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('TERRACED', 'Terraced house'), ('DORMITORY', 'Dormitory'), ('DUPLEX', 'Duplex'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
    ]
