# Generated by Django 2.2.12 on 2021-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_auto_20210118_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
