# Generated by Django 2.2.12 on 2021-01-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_auto_20210119_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='propertyTypePhotos/')),
            ],
            options={
                'verbose_name_plural': 'HomeTypes',
            },
        ),
        migrations.DeleteModel(
            name='PropertyTypeImage',
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('MANSION', 'Mansion'), ('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('SINGLEFAMILY', 'Single family'), ('OTHER', 'Other')], default='APARTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='home_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_type', to='listings.HomeType'),
        ),
    ]
