# Generated by Django 2.2.12 on 2021-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_rehgienpartner_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehgienpartner',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
