# Generated by Django 2.2.12 on 2020-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equity_Bank', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Cooperative_Bank', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Kcb_Bank', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'MortgageRates',
            },
        ),
    ]
