# Generated by Django 2.2.12 on 2020-10-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('1', 'Offensive Content'), ('2', 'Irrelevant Content'), ('3', 'Spam'), ('4', 'False content'), ('5', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('subject_user_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsPortfolioReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('1', 'Offensive Content'), ('2', 'Irrelevant Content'), ('3', 'Inaccurate information'), ('4', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('subject_user_id', models.PositiveIntegerField(null=True)),
                ('subject_item_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('1', 'Offensive Language'), ('2', 'Appears Fake'), ('3', 'Inaccurate review'), ('4', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('subject_user_id', models.PositiveIntegerField(null=True)),
                ('subject_item_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
