# Generated by Django 2.2.12 on 2020-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagereport',
            options={'verbose_name_plural': 'PageReports'},
        ),
        migrations.AlterModelOptions(
            name='projectsportfolioreport',
            options={'verbose_name_plural': 'ProjectsPortfolioReports'},
        ),
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'verbose_name_plural': 'ReviewReports'},
        ),
        migrations.AddField(
            model_name='pagereport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsportfolioreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
