# Generated by Django 2.2.12 on 2021-01-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rehgienpartner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RehgienPartner',
        ),
    ]
