# Generated by Django 2.2.12 on 2022-05-31 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=None, max_length=250, null=True)),
                ('recruiter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
                ('referrals', models.ManyToManyField(blank=True, related_name='recruiter_referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='ReferralPayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_payout', to='referral.Recruiter')),
            ],
        ),
    ]
