# Generated by Django 2.2.12 on 2022-06-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reward_price', models.PositiveIntegerField(default=0)),
                ('second_reward_price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Referral Systems',
            },
        ),
        migrations.AlterModelOptions(
            name='referralpayouts',
            options={'verbose_name_plural': 'Referral Payouts'},
        ),
        migrations.AddField(
            model_name='recruiter',
            name='referral_system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_referral_system', to='referral.ReferralSystem'),
        ),
    ]
