# Generated by Django 2.2.12 on 2022-01-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ANDROID', 'android'), ('APPLE', 'apple')], default=None, max_length=100)),
                ('name', models.CharField(max_length=250, null=True)),
                ('active', models.BooleanField(default=False)),
                ('device_id', models.UUIDField(default=None, null=True)),
                ('expo_token', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
