# Generated by Django 2.2.12 on 2022-04-30 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('CLIENT', 'client'), ('PRO', 'pro')], default=None, max_length=100)),
                ('platform', models.CharField(choices=[('ANDROID', 'android'), ('APPLE', 'apple')], default=None, max_length=100)),
                ('upgrade_type', models.CharField(choices=[('FORCEUPGRADE', 'force upgrade'), ('RECOMMENDUPGRADE', 'recommend upgrade')], default=None, max_length=100)),
                ('app_version', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Supported App Versions',
            },
        ),
    ]
