# Generated by Django 2.2.12 on 2021-01-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_descritpion', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, upload_to='partner_program_photos')),
            ],
        ),
        migrations.CreateModel(
            name='RehgienPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.URLField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('partner_program', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_program', to='partnership.PartnerProgram')),
            ],
            options={
                'verbose_name_plural': 'RehgienPartner',
            },
        ),
    ]
