# Generated by Django 2.2.12 on 2022-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceipt',
            name='reference',
            field=models.TextField(default=None, null=True),
        ),
    ]
