from django.urls import path, include
from django.conf.urls import url
from profiles.apis.views import (
                                UserListingsListApi,
                                UsersListAPI,
                                UserAccountEditApi,
                                UserProfileView,
                                NormalUserProfileListApi,
                                NormalUserProfileDetailApi,
                                NormalUserProfileUpdateApi,
                                AgentProfileListApi,
                                AgentProfileDetailApi,
                                AgentProfileUpdateApi,
                                AgentReviewsListApi,
                                AgentReviewsCreateApi,
                                PropertyManagerProfileListApi,
                                PropertyManagerProfileDetailApi,
                                PropertyManagerProfileUpdateApi,
                                PropertyManagerReviewsListApi,
                                PropertyManagerCreateApi,
                                DesignAndServiceProProfileListApi,
                                DesignAndServiceProProfileDetailApi,
                                DesignAndServiceProProfileUpdateApi,
                                DesignAndServiceProReviewsListApi,
                                DesignAndServiceProReviewsCreateApi,
                                    )

urlpatterns = [
    path('user/account/list/', UsersListAPI.as_view(), name='user_list' ),
    path('user/account/<int:pk>/edit/', UserAccountEditApi.as_view(), name='edit_account'),
    path('user/listings/', UserListingsListApi.as_view(), name='listings_list'),
    path('user/profiles/', UserProfileView.as_view(), name='user_profile'), #will be removed on next commit
    path('profiles/normalUsers/', NormalUserProfileListApi.as_view(), name='nUser_profiles'),
    path('profiles/normalUsers/<int:pk>/detail/', NormalUserProfileDetailApi.as_view(), name='nUser_detail'),
    path('profiles/normalUsers/<int:pk>/edit/', NormalUserProfileUpdateApi.as_view(), name='nUser_eProfile'),
    path('profiles/agents/', AgentProfileListApi.as_view(), name='agent_profiles'),
    path('profiles/agents/<int:pk>/detail/', AgentProfileDetailApi.as_view(), name='profile_detail'),
    path('profiles/agents/<int:pk>/edit/', AgentProfileUpdateApi.as_view(), name='agent_eProfile'),
    path('profiles/propertyManagers/', PropertyManagerProfileListApi.as_view(), name='pm_profiles'),
    path('profiles/propertyManagers/<int:pk>/detail/', PropertyManagerProfileDetailApi.as_view(), name='pm_detail'),
    path('profiles/propertyManagers/<int:pk>/edit/', PropertyManagerProfileUpdateApi.as_view(), name='pm_eProfile'),
    path('profiles/design&servicePros/', DesignAndServiceProProfileListApi.as_view(), name='ds_profiles'),
    path('profiles/design&servicePros/<int:pk>/detail/', DesignAndServiceProProfileDetailApi.as_view(), name='ds_detail'),
    path('profiles/design&servicePros/<int:pk>/edit/', DesignAndServiceProProfileUpdateApi.as_view(), name='ds_eProfile'),
    path('profiles/agentReviews/', AgentReviewsListApi.as_view(), name='agent_reviews'),
    path('profiles/agentReviews/create/', AgentReviewsCreateApi.as_view(), name='agent_rv_create'),
    path('profiles/propertyManagerReviews/', PropertyManagerReviewsListApi.as_view(), name='pm_reviews'),
    path('profiles/propertyManagerReviews/create/', PropertyManagerCreateApi.as_view(), name='pm_rv_create'),
    path('profiles/design&serviceProsReviews/', DesignAndServiceProReviewsListApi.as_view(), name='ds_reviews'),
    path('profiles/design&serviceProsReviews/create/', DesignAndServiceProReviewsCreateApi.as_view(), name='ds_rv_create'),
]
