# Generated by Django 2.2.12 on 2020-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20201204_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('CONDOMINIUM', 'Condominium'), ('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('MANSION', 'Mansion'), ('APARTMENT', 'Apartment')], default='APARTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinteraction',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
