# Generated by Django 2.2.12 on 2020-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20201204_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='deal_closed',
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('DORMITORY', 'Dormitory'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('SINGLEFAMILY', 'Single family'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('APARTMENT', 'Apartment'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex')], default='APARTMENT', max_length=20),
        ),
    ]
