# Generated by Django 2.2.12 on 2020-12-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20201205_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='deal_closed',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'yes')], default='YES', max_length=3),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('DORMITORY', 'Dormitory'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('MANSION', 'Mansion'), ('SINGLEFAMILY', 'Single family'), ('TERRACED', 'Terraced house'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20),
        ),
    ]
