# Generated by Django 2.2.12 on 2020-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20201211_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('MANSION', 'Mansion'), ('OTHER', 'Other'), ('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('DORMITORY', 'Dormitory'), ('TERRACED', 'Terraced house')], default='APARTMENT', max_length=20),
        ),
    ]
