# Generated by Django 2.2.12 on 2021-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_auto_20210109_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('TERRACED', 'Terraced house'), ('APARTMENT', 'Apartment'), ('SINGLEFAMILY', 'Single family'), ('DUPLEX', 'Duplex'), ('CONDOMINIUM', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other'), ('MANSION', 'Mansion'), ('BUNGALOW', 'Bungalow'), ('DORMITORY', 'Dormitory')], default='APARTMENT', max_length=20),
        ),
    ]
