# Generated by Django 2.2.12 on 2020-11-25 16:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201125_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('REALESTATE_VALUATION', 'realestate valuation'), ('LAND_VALUATION', 'land valuation'), ('PROPERTY_CONSULTANCY', 'property consultancy'), ('BUYING_AND_SELLING_PROPERTY', 'buying and selling property'), ('PROPERTY_LISTING', 'property listing'), ('PROPERTY_MANAGEMENT', 'property management'), ('FACILITY_MANAGEMENT', 'facility management'), ('BUILDING_CONDITION_ASSESSMENT', 'building condition asessment'), ('LAND_SERVEYING', 'land surveying')], default=None, max_length=100, null=True),
        ),
    ]
