# Generated by Django 2.2.12 on 2020-12-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201130_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='attention_to_detail',
        ),
        migrations.RemoveField(
            model_name='review',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='review',
            name='negotiation_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
