# Generated by Django 2.2.12 on 2021-01-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_remove_businessprofile_service_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='service_area2',
            new_name='service_areas',
        ),
    ]
