# Generated by Django 2.2.12 on 2021-10-15 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_professionalservice_professional_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('search_date', models.DateTimeField(auto_now=True, null=True)),
                ('professional_service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_service_search_history', to='profiles.ProfessionalService')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_service_search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ServiceSearchHistory',
            },
        ),
    ]
