# Generated by Django 2.2.12 on 2021-10-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_kenyatown'),
        ('profiles', '0052_clientanswer_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='proanswer',
            name='service_delivery_areas',
            field=models.ManyToManyField(related_name='pro_service_delivery_areas', to='location.KenyaTown'),
        ),
        migrations.AlterField(
            model_name='clientanswer',
            name='project_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_project_location', to='location.KenyaTown'),
        ),
    ]
