# Generated by Django 2.2.12 on 2021-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_auto_20211021_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_token_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
